package com.rathod.multiThreading;
class NameRunnabl implements Runnable 
{
	public void run()
	{
		for (int x=1;x<=50 ;x++ )
		{
			System.out.println("Run by "+ Thread.currentThread().getName() + " X is "+ x);
		}
	}
}
public class ManyNames1
{    
	public static void main(String[] args) 
	{
		NameRunnabl nr=new NameRunnabl();
		
		Thread one=new Thread(nr);
		Thread two=new Thread(nr);
		Thread three=new Thread(nr);

		one.setName("   Arun ");
		two.setName("   Ankita");
		three.setName(" Nikita");

		one.start();
		two.start();
		three.start();
		
	}
}

/*
Run by    Arun  X is 266
Run by    Ankita X is 242
Run by    Arun  X is 267
Run by    Arun  X is 268
Run by    Arun  X is 269
Run by    Ankita X is 243
Run by    Arun  X is 270
Run by    Ankita X is 244
Run by    Arun  X is 271
Run by    Arun  X is 272
Run by    Arun  X is 273
Run by    Arun  X is 274
Run by    Arun  X is 275
Run by    Arun  X is 276
Run by    Ankita X is 245
Run by    Arun  X is 277
Run by    Arun  X is 278
Run by    Ankita X is 246
Run by    Arun  X is 279
Run by    Ankita X is 247
Run by    Arun  X is 280
Run by    Arun  X is 281
Run by    Arun  X is 282
Run by    Ankita X is 248
Run by    Arun  X is 283
Run by    Arun  X is 284
Run by    Arun  X is 285
Run by    Ankita X is 249
Run by    Arun  X is 286
Run by    Ankita X is 250
Run by    Arun  X is 287
Run by    Ankita X is 251
Run by    Ankita X is 252
Run by    Ankita X is 253
Run by    Ankita X is 254
Run by    Ankita X is 255
Run by    Ankita X is 256
Run by    Ankita X is 257
Run by    Ankita X is 258
Run by    Arun  X is 288
Run by    Arun  X is 289
Run by    Arun  X is 290
Run by    Arun  X is 291
Run by    Arun  X is 292
Run by    Arun  X is 293
Run by    Arun  X is 294
Run by    Arun  X is 295
Run by    Arun  X is 296
Run by    Arun  X is 297
Run by    Arun  X is 298
Run by    Arun  X is 299
Run by    Arun  X is 300
Run by    Arun  X is 301
Run by    Arun  X is 302
Run by    Arun  X is 303
Run by    Arun  X is 304
Run by    Arun  X is 305
Run by    Arun  X is 306
Run by    Arun  X is 307
Run by    Arun  X is 308
Run by    Arun  X is 309
Run by    Arun  X is 310
Run by    Arun  X is 311
Run by    Arun  X is 312
Run by    Arun  X is 313
Run by    Arun  X is 314
Run by    Arun  X is 315
Run by    Arun  X is 316
Run by    Arun  X is 317
Run by    Arun  X is 318
Run by    Arun  X is 319
Run by    Arun  X is 320
Run by    Arun  X is 321
Run by    Arun  X is 322
Run by    Arun  X is 323
Run by    Arun  X is 324
Run by    Arun  X is 325
Run by    Arun  X is 326
Run by    Arun  X is 327
Run by    Arun  X is 328
Run by    Arun  X is 329
Run by    Arun  X is 330
Run by    Arun  X is 331
Run by    Arun  X is 332
Run by    Arun  X is 333
Run by    Arun  X is 334
Run by    Arun  X is 335
Run by    Arun  X is 336
Run by    Arun  X is 337
Run by    Arun  X is 338
Run by    Arun  X is 339
Run by    Arun  X is 340
Run by    Arun  X is 341
Run by    Ankita X is 259
Run by    Arun  X is 342
Run by    Ankita X is 260
Run by    Arun  X is 343
Run by    Ankita X is 261
Run by    Arun  X is 344
Run by    Ankita X is 262
Run by    Arun  X is 345
Run by    Arun  X is 346
Run by    Arun  X is 347
Run by    Arun  X is 348
Run by    Arun  X is 349
Run by    Ankita X is 263
Run by    Arun  X is 350
Run by    Ankita X is 264
Run by    Arun  X is 351
Run by    Ankita X is 265
Run by    Arun  X is 352
Run by    Ankita X is 266
Run by    Arun  X is 353
Run by    Ankita X is 267
Run by    Arun  X is 354
Run by    Arun  X is 355
Run by    Ankita X is 268
Run by    Arun  X is 356
Run by    Ankita X is 269
Run by    Arun  X is 357
Run by    Arun  X is 358
Run by    Arun  X is 359
Run by    Arun  X is 360
Run by    Arun  X is 361
Run by    Arun  X is 362
Run by    Arun  X is 363
Run by    Arun  X is 364
Run by    Arun  X is 365
Run by    Arun  X is 366
Run by    Arun  X is 367
Run by    Arun  X is 368
Run by    Ankita X is 270
Run by    Arun  X is 369
Run by    Ankita X is 271
Run by    Ankita X is 272
Run by    Arun  X is 370
Run by    Ankita X is 273
Run by    Arun  X is 371
Run by    Arun  X is 372
Run by    Arun  X is 373
Run by    Ankita X is 274
Run by    Arun  X is 374
Run by    Ankita X is 275
Run by    Arun  X is 375
Run by    Ankita X is 276
Run by    Arun  X is 376
Run by    Arun  X is 377
Run by    Arun  X is 378
Run by    Arun  X is 379
Run by    Ankita X is 277
Run by    Arun  X is 380
Run by    Ankita X is 278
Run by    Arun  X is 381
Run by    Ankita X is 279
Run by    Arun  X is 382
Run by    Arun  X is 383
Run by    Ankita X is 280
Run by    Arun  X is 384
Run by    Arun  X is 385
Run by    Ankita X is 281
Run by    Arun  X is 386
Run by    Ankita X is 282
Run by    Arun  X is 387
Run by    Ankita X is 283
Run by    Arun  X is 388
Run by    Ankita X is 284
Run by    Arun  X is 389
Run by    Arun  X is 390
Run by    Ankita X is 285
Run by    Arun  X is 391
Run by    Ankita X is 286
Run by    Arun  X is 392
Run by    Ankita X is 287
Run by    Arun  X is 393
Run by    Arun  X is 394
Run by    Arun  X is 395
Run by    Arun  X is 396
Run by    Arun  X is 397
Run by    Ankita X is 288
Run by    Arun  X is 398
Run by    Ankita X is 289
Run by    Arun  X is 399
Run by    Arun  X is 400
Run by    Ankita X is 290
Run by    Ankita X is 291
Run by    Ankita X is 292
Run by    Ankita X is 293
Run by    Ankita X is 294
Run by    Ankita X is 295
Run by    Ankita X is 296
Run by    Ankita X is 297
Run by    Ankita X is 298
Run by    Ankita X is 299
Run by    Ankita X is 300
Run by    Ankita X is 301
Run by    Ankita X is 302
Run by    Ankita X is 303
Run by    Ankita X is 304
Run by    Ankita X is 305
Run by    Ankita X is 306
Run by    Ankita X is 307
Run by    Ankita X is 308
Run by    Ankita X is 309
Run by    Ankita X is 310
Run by    Ankita X is 311
Run by    Ankita X is 312
Run by    Ankita X is 313
Run by    Ankita X is 314
Run by    Ankita X is 315
Run by    Ankita X is 316
Run by    Ankita X is 317
Run by    Ankita X is 318
Run by    Ankita X is 319
Run by    Ankita X is 320
Run by    Ankita X is 321
Run by    Ankita X is 322
Run by    Ankita X is 323
Run by    Ankita X is 324
Run by    Ankita X is 325
Run by    Ankita X is 326
Run by    Ankita X is 327
Run by    Ankita X is 328
Run by    Ankita X is 329
Run by    Ankita X is 330
Run by    Ankita X is 331
Run by    Ankita X is 332
Run by    Ankita X is 333
Run by    Ankita X is 334
Run by    Ankita X is 335
Run by    Ankita X is 336
Run by    Ankita X is 337
Run by    Ankita X is 338
Run by    Ankita X is 339
Run by    Ankita X is 340
Run by    Ankita X is 341
Run by    Ankita X is 342
Run by    Ankita X is 343
Run by    Ankita X is 344
Run by    Ankita X is 345
Run by    Ankita X is 346
Run by    Ankita X is 347
Run by    Ankita X is 348
Run by    Ankita X is 349
Run by    Ankita X is 350
Run by    Ankita X is 351
Run by    Ankita X is 352
Run by    Ankita X is 353
Run by    Ankita X is 354
Run by    Ankita X is 355
Run by    Ankita X is 356
Run by    Ankita X is 357
Run by    Ankita X is 358
Run by    Ankita X is 359
Run by    Ankita X is 360
Run by    Ankita X is 361
Run by    Ankita X is 362
Run by    Ankita X is 363
Run by    Ankita X is 364
Run by    Ankita X is 365
Run by    Ankita X is 366
Run by    Ankita X is 367
Run by    Ankita X is 368
Run by    Ankita X is 369
Run by    Ankita X is 370
Run by    Ankita X is 371
Run by    Ankita X is 372
Run by    Ankita X is 373
Run by    Ankita X is 374
Run by    Ankita X is 375
Run by    Ankita X is 376
Run by    Ankita X is 377
Run by    Ankita X is 378
Run by    Ankita X is 379
Run by    Ankita X is 380
Run by    Ankita X is 381
Run by    Ankita X is 382
Run by    Ankita X is 383
Run by    Ankita X is 384
Run by    Ankita X is 385
Run by    Ankita X is 386
Run by    Ankita X is 387
Run by    Ankita X is 388
Run by    Ankita X is 389
Run by    Ankita X is 390
Run by    Ankita X is 391
Run by    Ankita X is 392
Run by    Ankita X is 393
Run by    Ankita X is 394
Run by    Ankita X is 395
Run by    Ankita X is 396
Run by    Ankita X is 397
Run by    Ankita X is 398
Run by    Ankita X is 399
Run by    Ankita X is 400

G:\SCJP\Scjp6\ch9-Threads>/p
'/p' is not recognized as an int
operable program or batch file.

G:\SCJP\Scjp6\ch9-Threads>


G:\SCJP\Scjp6\ch9-Threads>javac ManyNames1.java

G:\SCJP\Scjp6\ch9-Threads>java ManyNames1
Run by    Ankita X is 1
Run by    Ankita X is 2
Run by    Ankita X is 3
Run by    Arun  X is 1
Run by    Arun  X is 2
Run by  Nikita X is 1
Run by    Arun  X is 3
Run by    Ankita X is 4
Run by    Arun  X is 4
Run by  Nikita X is 2
Run by    Arun  X is 5
Run by    Ankita X is 5
Run by    Arun  X is 6
Run by    Arun  X is 7
Run by  Nikita X is 3
Run by  Nikita X is 4
Run by  Nikita X is 5
Run by  Nikita X is 6
Run by  Nikita X is 7
Run by    Arun  X is 8
Run by    Arun  X is 9
Run by    Arun  X is 10
Run by    Arun  X is 11
Run by    Arun  X is 12
Run by    Arun  X is 13
Run by    Arun  X is 14
Run by    Arun  X is 15
Run by    Arun  X is 16
Run by    Ankita X is 6
Run by    Ankita X is 7
Run by    Arun  X is 17
Run by    Arun  X is 18
Run by    Arun  X is 19
Run by    Arun  X is 20
Run by    Arun  X is 21
Run by    Arun  X is 22
Run by    Arun  X is 23
Run by    Arun  X is 24
Run by    Arun  X is 25
Run by  Nikita X is 8
Run by    Arun  X is 26
Run by    Ankita X is 8
Run by    Arun  X is 27
Run by    Arun  X is 28
Run by    Arun  X is 29
Run by  Nikita X is 9
Run by  Nikita X is 10
Run by  Nikita X is 11
Run by  Nikita X is 12
Run by  Nikita X is 13
Run by  Nikita X is 14
Run by    Arun  X is 30
Run by    Arun  X is 31
Run by    Ankita X is 9
Run by    Arun  X is 32
Run by  Nikita X is 15
Run by    Arun  X is 33
Run by    Ankita X is 10
Run by    Arun  X is 34
Run by  Nikita X is 16
Run by    Arun  X is 35
Run by    Ankita X is 11
Run by    Arun  X is 36
Run by  Nikita X is 17
Run by  Nikita X is 18
Run by  Nikita X is 19
Run by  Nikita X is 20
Run by  Nikita X is 21
Run by    Arun  X is 37
Run by    Ankita X is 12
Run by    Arun  X is 38
Run by    Arun  X is 39
Run by    Arun  X is 40
Run by    Arun  X is 41
Run by  Nikita X is 22
Run by    Arun  X is 42
Run by    Arun  X is 43
Run by    Arun  X is 44
Run by    Arun  X is 45
Run by    Arun  X is 46
Run by    Arun  X is 47
Run by    Arun  X is 48
Run by    Arun  X is 49
Run by    Arun  X is 50
Run by    Ankita X is 13
Run by  Nikita X is 23
Run by    Ankita X is 14
Run by    Ankita X is 15
Run by  Nikita X is 24
Run by    Ankita X is 16
Run by  Nikita X is 25
Run by    Ankita X is 17
Run by  Nikita X is 26
Run by  Nikita X is 27
Run by  Nikita X is 28
Run by  Nikita X is 29
Run by    Ankita X is 18
Run by  Nikita X is 30
Run by  Nikita X is 31
Run by    Ankita X is 19
Run by    Ankita X is 20
Run by    Ankita X is 21
Run by    Ankita X is 22
Run by  Nikita X is 32
Run by    Ankita X is 23
Run by  Nikita X is 33
Run by    Ankita X is 24
Run by  Nikita X is 34
Run by    Ankita X is 25
Run by  Nikita X is 35
Run by    Ankita X is 26
Run by    Ankita X is 27
Run by    Ankita X is 28
Run by    Ankita X is 29
Run by    Ankita X is 30
Run by    Ankita X is 31
Run by    Ankita X is 32
Run by    Ankita X is 33
Run by    Ankita X is 34
Run by    Ankita X is 35
Run by  Nikita X is 36
Run by    Ankita X is 36
Run by  Nikita X is 37
Run by  Nikita X is 38
Run by  Nikita X is 39
Run by  Nikita X is 40
Run by    Ankita X is 37
Run by  Nikita X is 41
Run by    Ankita X is 38
Run by  Nikita X is 42
Run by    Ankita X is 39
Run by  Nikita X is 43
Run by    Ankita X is 40
Run by    Ankita X is 41
Run by  Nikita X is 44
Run by    Ankita X is 42
Run by  Nikita X is 45
Run by    Ankita X is 43
Run by  Nikita X is 46
Run by    Ankita X is 44
Run by  Nikita X is 47
Run by    Ankita X is 45
Run by  Nikita X is 48
Run by    Ankita X is 46
Run by  Nikita X is 49
Run by  Nikita X is 50
Run by    Ankita X is 47
Run by    Ankita X is 48
Run by    Ankita X is 49
Run by    Ankita X is 50

G:\SCJP\Scjp6\ch9-Threads>
*/